[tool.black]
line-length = 120
[tool.isort]
profile = 'black'
line_length = 120
force_single_line = true
skip_glob = [".env"]
[tool.pylint.'MASTER']
max-line-length=120
[tool.pylint.messages_control]
disable =[
    'broad-except',
    'duplicate-code',
    'fixme',
    'import-error',
    'invalid-name',
    'line-too-long',
    'protected-access',
    "missing-module-docstring",
    'missing-function-docstring',
    'raise-missing-from',
    'redefined-builtin',
    'redefined-outer-name',
    'subprocess-run-check',
    'too-few-public-methods',
    'too-many-locals',
    'too-many-arguments',
    'too-many-instance-attributes',
    'too-many-statements',
    'trailing-whitespace',
    'ungrouped-imports',
    'unspecified-encoding',
    'unused-argument',
    'wrong-import-order',
]